import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import { NotificationBell } from "@/components/NotificationBell";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="sticky top-0 z-40 border-b bg-background">
          <div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-3">
            <nav className="flex items-center gap-4 text-sm">
              <Link className="font-semibold" href="/farmer">
                AgriLens
              </Link>
              <Link className="text-muted-foreground hover:text-foreground" href="/farmer">
                Farmer
              </Link>
              <Link className="text-muted-foreground hover:text-foreground" href="/produce">
                Produce
              </Link>
              <Link
                className="text-muted-foreground hover:text-foreground"
                href="/notifications"
              >
                Notifications
              </Link>
            </nav>
            <NotificationBell />
          </div>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
